# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nflmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(default='k', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(default='s', max_length=20),
            preserve_default=False,
        ),
    ]
