# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nflmap', '0002_auto_20161204_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.CharField(default='s', max_length=150),
            preserve_default=False,
        ),
    ]
