# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nflmap', '0003_player_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nflmap.College'),
        ),
        migrations.AlterField(
            model_name='player',
            name='highschool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nflmap.HighSchool'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nflmap.Team'),
        ),
    ]
