# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nflmap', '0004_auto_20161204_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='url',
        ),
        migrations.AddField(
            model_name='player',
            name='nflid',
            field=models.IntegerField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='l', max_length=5),
            preserve_default=False,
        ),
    ]
