# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 04:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nflmap', '0007_auto_20161204_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
